<?php $this->layout('layout::default', ['title' => 'Enter code']) ?>

<div class="govuk-width-container">

    <?php $this->insert('snippet::phase-banner') ?>

    <a href="/" class="govuk-back-link">Back</a>

    <main class="govuk-main-wrapper">

        <div class="govuk-grid-row">
            <div class="govuk-grid-column-one">
                <h1 class="govuk-heading-xl">Enter Code</h1>

                <?php if (!empty($errorMsg)) { ?>
                    <div class="govuk-error-summary" aria-labelledby="error-summary-title" role="alert" tabindex="-1" data-module="error-summary">
                        <h2 class="govuk-error-summary__title" id="error-summary-title">
                            There is a problem
                        </h2>
                        <div class="govuk-error-summary__body">
                            <ul class="govuk-list govuk-error-summary__list">
                                <li>
                                    <a href="#share-code"><?= $errorMsg; ?></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                <?php } ?>

                <div class="govuk-grid-row">
                    <div class="govuk-grid-column-one-half">

                        <form method="post" action="/enter-code">
                            <fieldset class="govuk-fieldset">

                                <div class="govuk-form-group <?= (empty($errorMsg) ? '' : 'govuk-form-group--error') ?>">

                                    <div class="govuk-form-group">
                                        <label class="govuk-label" for="share-code">
                                            LPA code
                                        </label>

                                        <?php if (!empty($errorMsg)) { ?>
                                            <span id="passport-issued-error" class="govuk-error-message">
                                                <span class="govuk-visually-hidden">Error:</span> <?= $errorMsg; ?>
                                            </span>
                                        <?php } ?>

                                        <input class="govuk-input <?= (empty($errorMsg) ? '' : 'govuk-input--error') ?>" id="share-code" name="share-code" type="text">
                                    </div>

                                </div>

                                <details class="govuk-details">
                                    <summary class="govuk-details__summary">
                                        <span class="govuk-details__summary-text">
                                            What is a share code?
                                        </span>
                                    </summary>
                                    <div class="govuk-details__text">
                                        A share code is given to you by the donor or an attorney named on the lasting power
                                        of attorney.
                                    </div>
                                </details>

                                <button type="submit" class="govuk-button">Save and continue</button>

                            </fieldset>
                        </form>

                    </div>
                </div>

            </div>
        </div>

    </main>
</div>
