<?php $this->layout('layout::default', ['title' => 'Enter code']) ?>

<div class="govuk-width-container">

    <?php $this->insert('snippet::phase-banner') ?>

    <main class="govuk-main-wrapper">
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-one-half">
                <h1 class="govuk-heading-xl">Use your LPA Homepage</h1>

                <a href="/enter-code" role="button" draggable="false" class="govuk-button govuk-button--start">
                    Start now
                </a>

            </div>
        </div>

    </main>
</div>
