<?php $this->layout('layout::default', ['title' => 'View LPA']) ?>

<style>
    .logo {
        padding: 40px 0 0 10px;
        background-image: url(/assets/images/org-crest.png);
        background-position: 9px top;
        border-left: 2px solid;
        background-repeat: no-repeat;
    }

    .logo p {
        position: relative;
        top: 3px;
        font-family: Helvetica, Arial;
        font-size: 27px;
    }

    .govuk-table caption {
        margin-bottom: 10px;
    }

    .govuk-table tbody {
        border-top: 1px solid #bfc1c3;
        border-bottom: 1px solid #bfc1c3;
    }

    .govuk-table .govuk-table__header,
    .govuk-table .govuk-table__cell {
        border-bottom-width: 0;
    }

    .govuk-table tr.underline {
        border-bottom: 1px solid #bfc1c3;
    }

</style>

<div class="govuk-width-container">

    <?php $this->insert('snippet::phase-banner') ?>

    <main class="govuk-main-wrapper">

        <div class="govuk-grid-row">

            <div class="govuk-grid-column-two-thirds">
                <h1 class="govuk-heading-l"><?= $lpa->donor->name->first; ?> <?= $lpa->donor->name->last; ?>'s <?= ($lpa->type === 'property-and-financial' ? 'property and finance' : 'health and welfare'); ?> LPA</h1>
            </div>

            <div class="govuk-grid-column-one-third">
                <div class="logo">
                    <p class="govuk-body-l">Office of the<br/>Public Guardian</p>
                </div>
            </div>

        </div>

        <div class="govuk-grid-row">

            <div class="govuk-grid-column-full">

                <div class="govuk-panel govuk-panel--confirmation">

                    <h1 class="govuk-panel__title">This LPA is <?= ($lpa->isValid ? 'valid' : 'invalid') ?></h1>

                    <div class="govuk-panel__body govuk-!-font-size-24">Status last confirmed on <?= $lpa->dateLastConfirmedStatus; ?></div>

                    <br/>

                    <div class="govuk-panel__body govuk-!-font-size-24"><?= ($lpa->decisions->when === 'no-capacity' ? 'This LPA can only be used when the donor does not have mental capacity' : '??'); ?></div>

                </div>

                <br/>

                <p class="govuk-body">
                    You can <a href="#" class="govuk-link">download</a> a copy of this page. Portable document format (PDF)
                </p>

                <br/>

                <table class="govuk-table">

                    <caption class="govuk-table__caption">The donor</caption>

                    <tbody class="govuk-table__body">
                        <tr class="govuk-table__row">
                            <th class="govuk-table__header govuk-!-width-one-third" scope="row">Name</th>
                            <td class="govuk-table__cell"><?= $lpa->donor->name->title; ?> <?= $lpa->donor->name->first; ?> <?= $lpa->donor->name->last; ?></td>
                        </tr>
                        <tr class="govuk-table__row">
                            <th class="govuk-table__header govuk-!-width-one-third" scope="row">Date of birth</th>
                            <td class="govuk-table__cell"><?= $lpa->donor->dob; ?></td>
                        </tr>
                        <tr class="govuk-table__row underline">
                            <th class="govuk-table__header govuk-!-width-one-third" scope="row">Address</th>
                            <td class="govuk-table__cell"><?= $lpa->donor->address; ?></td>
                        </tr>
                        <tr class="govuk-table__row">
                            <th class="govuk-table__header govuk-!-width-one-third" scope="row">How decisions are made</th>
                            <td class="govuk-table__cell"><?= ($lpa->decisions->how === 'jointly' ? 'The attorneys must act jointly' : '??'); ?></td>
                        </tr>
                    </tbody>

                </table>

                <?php
                    $ordinals = ['th', 'st', 'nd', 'rd', 'th', 'th', 'th', 'th', 'th', 'th'];

                    foreach ($lpa->attorneys as $idx => $attorney) {
                        $number = $idx + 1;

                        $ordinal = (in_array($number, [11, 12, 13]) ? 'th' : $ordinals[$number % 10]); ?>

                        <table class="govuk-table">

                            <caption class="govuk-table__caption"><?= $number . $ordinal; ?> Attorney</caption>

                            <tbody class="govuk-table__body">
                                <tr class="govuk-table__row">
                                    <th class="govuk-table__header govuk-!-width-one-third" scope="row">Name</th>
                                    <td class="govuk-table__cell"><?= $attorney->name->title; ?> <?= $attorney->name->first; ?> <?= $attorney->name->last; ?></td>
                                </tr>
                                <tr class="govuk-table__row">
                                    <th class="govuk-table__header govuk-!-width-one-third" scope="row">Date of birth</th>
                                    <td class="govuk-table__cell"><?= $attorney->dob; ?></td>
                                </tr>
                                <tr class="govuk-table__row underline">
                                    <th class="govuk-table__header govuk-!-width-one-third" scope="row">Address</th>
                                    <td class="govuk-table__cell"><?= $attorney->address; ?></td>
                                </tr>
                            </tbody>

                        </table>

                    <?php }
                ?>

                <table class="govuk-table">

                    <caption class="govuk-table__caption">LPA details</caption>

                    <tbody class="govuk-table__body">
                        <tr class="govuk-table__row">
                            <th class="govuk-table__header govuk-!-width-one-third" scope="row">Preferences</th>
                            <td class="govuk-table__cell"><?= ($lpa->preferences ? 'Yes' : 'No'); ?></td>
                        </tr>
                        <tr class="govuk-table__row">
                            <th class="govuk-table__header govuk-!-width-one-third" scope="row">Instructions</th>
                            <td class="govuk-table__cell"><?= ($lpa->instructions ? 'Yes' : 'No'); ?></td>
                        </tr>
                        <tr class="govuk-table__row">
                            <th class="govuk-table__header govuk-!-width-one-third" scope="row">Date donor signed LPA</th>
                            <td class="govuk-table__cell"><?= $lpa->dateDonorSigned; ?></td>
                        </tr>
                        <tr class="govuk-table__row">
                            <th class="govuk-table__header govuk-!-width-one-third" scope="row">Registration date</th>
                            <td class="govuk-table__cell"><?= $lpa->dateRegistration; ?></td>
                        </tr>
                        <tr class="govuk-table__row">
                            <th class="govuk-table__header govuk-!-width-one-third" scope="row">When can the LPA be used?</th>
                            <td class="govuk-table__cell"><?= ($lpa->decisions->when === 'no-capacity' ? 'When the donor does not have mental capacity' : '??'); ?></td>
                        </tr>
                        <tr class="govuk-table__row">
                            <th class="govuk-table__header govuk-!-width-one-third" scope="row">LPA case number</th>
                            <td class="govuk-table__cell"><?= trim(chunk_split(sprintf("%011d", $lpa->caseNumber), 4, ' ')); ?></td>
                        </tr>
                    </tbody>

                </table>

            </div>

        </div>

    </main>
</div>
