services:

  zap:
    profiles:
      - tools
    build:
      context: zap

  lpa-codes-pact-mock:
    image: pactfoundation/pact-cli:latest-multi@sha256:328565c63fcd516c91ab9a3787231424e55ba22c05b082ab648dd67d841b47d9
    command:
      - mock-service
      - -p
      - "80"
      - --host
      - "0.0.0.0"
      - --pact-dir
      - /tmp/pacts
      - --consumer
      - use-an-lpa
      - --provider
      - data-lpa-codes
    volumes:
      - ./service-api/app/build/pacts:/tmp/pacts

  api-gateway-pact-mock:
    image: pactfoundation/pact-cli:latest-multi@sha256:328565c63fcd516c91ab9a3787231424e55ba22c05b082ab648dd67d841b47d9
    command:
      - mock-service
      - -p
      - "80"
      - --host
      - "0.0.0.0"
      - --pact-dir
      - /tmp/pacts
      - --consumer
      - use-an-lpa
      - --provider
      - data-lpa
    volumes:
      - ./service-api/app/build/pacts:/tmp/pacts

  iap-images-mock:
    image: pactfoundation/pact-cli:latest-multi@sha256:328565c63fcd516c91ab9a3787231424e55ba22c05b082ab648dd67d841b47d9
    command:
      - mock-service
      - -p
      - "80"
      - --host
      - "0.0.0.0"
      - --pact-dir
      - /tmp/pacts
      - --consumer
      - use-an-lpa
      - --provider
      - data-lpa-instructions-preferences
    volumes:
      - ./service-api/app/build/pacts:/tmp/pacts

  api-app:
    image: api-app
    depends_on:
      - lpa-codes-pact-mock
      - api-gateway-pact-mock
      - iap-images-mock
