services:

  zap:
    profiles:
      - tools
    build:
      context: zap

  lpa-codes-pact-mock:
    image: pactfoundation/pact-cli:latest-multi
    ports:
      - 1234:80
    command:
      - mock-service
      - -p
      - "80"
      - --host
      - "0.0.0.0"
      - --pact-dir
      - /tmp/pacts
      - --consumer
      - use_a_lasting_power_of_attorney
      - --provider
      - lpa-codes
    volumes:
      - ./service-api/app/test/pacts:/tmp/pacts

  api-gateway-pact-mock:
    image: pactfoundation/pact-cli:latest-multi
    command:
      - mock-service
      - -p
      - "80"
      - --host
      - "0.0.0.0"
      - --pact-dir
      - /tmp/pacts
      - --consumer
      - use_a_lasting_power_of_attorney
      - --provider
      - api-gateway
    volumes:
      - ./service-api/app/test/pacts:/tmp/pacts

  iap-images-mock:
    image: pactfoundation/pact-cli:latest-multi
    command:
      - mock-service
      - -p
      - "80"
      - --host
      - "0.0.0.0"
      - --pact-dir
      - /tmp/pacts
      - --consumer
      - use_a_lasting_power_of_attorney
      - --provider
      - iap-api-gateway
    volumes:
      - ./service-api/app/test/pacts:/tmp/pacts

  api-app:
    image: api-app
    depends_on:
      - lpa-codes-pact-mock
      - api-gateway-pact-mock
      - iap-images-mock
