version: "3.8"

volumes:
  webpack_dist:

services:

  zap:
    build:
      context: zap

  smoke-tests:
    build:
      context: .
      dockerfile: tests/smoke/Dockerfile
    volumes:
      - ./tests/smoke:/home/circleci/project
      - ./tests/features:/home/circleci/project/features
    environment:
      BEHAT_VIEWER_URL: http://viewer-web
      BEHAT_ACTOR_URL: http://actor-web
      BEHAT_OLD_VIEWER_URL: http://viewer-web
      BEHAT_OLD_ACTOR_URL: http://actor-web

  lpa-codes-pact-mock:
    image: pactfoundation/pact-cli:latest
    ports:
        - 1234:80
    command:
        - mock-service
        - -p
        - "80"
        - --host
        - "0.0.0.0"
        - --pact-dir
        - /tmp/pacts
        - --consumer
        - use_a_lasting_power_of_attorney
        - --provider
        - lpa-codes

  api-gateway-pact-mock:
    image: pactfoundation/pact-cli:latest
    command:
      - mock-service
      - -p
      - "80"
      - --host
      - "0.0.0.0"
      - --pact-dir
      - /tmp/pacts
      - --consumer
      - use_a_lasting_power_of_attorney
      - --provider
      - api-gateway

  api-app:
    image: api-app
    depends_on:
      - lpa-codes-pact-mock
      - api-gateway-pact-mock
