version: "3.8"

volumes:
  webpack_dist:

services:

  zap:
    profiles:
      - tools
    build:
      context: zap
    environment:
      ULPA_USER: opg-use-an-lpa+test-user@digital.justice.gov.uk
      ULPA_PWORD: umlTest1
      ULPA_URI: https://host.docker.internal:9042/
    volumes:
      - ./zap/report:/zap/report

  smoke-tests:
    profiles:
      - testing
    build:
      context: .
      dockerfile: tests/smoke/Dockerfile
    volumes:
      - ./tests/smoke:/app
      - ./tests/features:/app/features
    environment:
      BEHAT_VIEWER_URL: http://proxy:9001
      BEHAT_ACTOR_URL: http://proxy:9002
      BEHAT_OLD_VIEWER_URL: http://proxy:9001
      BEHAT_OLD_ACTOR_URL: http://proxy:9002
      BEHAT_PARAMS: '{"extensions":{"Smoke\\SmokeExtension":{"allow_insecure_https":true}}}'
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000
      XDEBUG_MODE: develop,debug,coverage

  lpa-codes-pact-mock:
    profiles:
      - testing
    image: pactfoundation/pact-cli:latest-multi
    ports:
        - 1234:80
    command:
        - mock-service
        - -p
        - "80"
        - --host
        - "0.0.0.0"
        - --pact-dir
        - /tmp/pacts
        - --consumer
        - use_a_lasting_power_of_attorney
        - --provider
        - lpa-codes

  api-gateway-pact-mock:
    profiles:
      - testing
    image: pactfoundation/pact-cli:latest-multi
    command:
      - mock-service
      - -p
      - "80"
      - --host
      - "0.0.0.0"
      - --pact-dir
      - /tmp/pacts
      - --consumer
      - use_a_lasting_power_of_attorney
      - --provider
      - api-gateway

  iap-images-mock:
    profiles:
      - testing
    image: pactfoundation/pact-cli:latest-multi
    command:
      - mock-service
      - -p
      - "80"
      - --host
      - "0.0.0.0"
      - --pact-dir
      - /tmp/pacts
      - --consumer
      - use_a_lasting_power_of_attorney
      - --provider
      - iap-api-gateway

  api-app:
    profiles:
      - testing
    image: api-app
    depends_on:
      - lpa-codes-pact-mock
      - api-gateway-pact-mock
      - iap-images-mock
