services:

  zap:
    profiles:
      - tools
    build:
      context: zap

  lpa-codes-pact-mock:
    profiles:
      - testing
    image: pactfoundation/pact-cli:latest-multi
    ports:
        - 1234:80
    command:
        - mock-service
        - -p
        - "80"
        - --host
        - "0.0.0.0"
        - --pact-dir
        - /tmp/pacts
        - --consumer
        - use_a_lasting_power_of_attorney
        - --provider
        - lpa-codes

  api-gateway-pact-mock:
    profiles:
      - testing
    image: pactfoundation/pact-cli:latest-multi
    command:
      - mock-service
      - -p
      - "80"
      - --host
      - "0.0.0.0"
      - --pact-dir
      - /tmp/pacts
      - --consumer
      - use_a_lasting_power_of_attorney
      - --provider
      - api-gateway

  iap-images-mock:
    profiles:
      - testing
    image: pactfoundation/pact-cli:latest-multi
    command:
      - mock-service
      - -p
      - "80"
      - --host
      - "0.0.0.0"
      - --pact-dir
      - /tmp/pacts
      - --consumer
      - use_a_lasting_power_of_attorney
      - --provider
      - iap-api-gateway

  api-app:
    profiles:
      - testing
    image: api-app
    depends_on:
      - lpa-codes-pact-mock
      - api-gateway-pact-mock
      - iap-images-mock
