server {
    server_name gateway;
    listen 5000 default_server;

    location /v1/image-request/ {
        proxy_pass http://mock-image-request-handler:4012;
    }

    location / {
        root /var/www/html;
    }
}
