[http]
[http.middlewares]

[http.middlewares.viewer-gov-redirect.redirectRegex]
regex="^https://[^/]+/$$"
replacement="https://www.gov.uk/view-lasting-power-of-attorney"

[http.middlewares.actor-gov-redirect.redirectRegex]
regex="^https://[^/]+/$$"
replacement="https://www.gov.uk/use-lasting-power-of-attorney"

[http.middlewares.viewer-web-https.redirectScheme]
scheme="https"
port=9041

[http.middlewares.actor-web-https.redirectScheme]
scheme="https"
port=9042

[http.routers]
[http.routers.viewer-web]
rule="PathPrefix(`/`)"
entryPoints="http-viewer"
middlewares=["viewer-web-https"]
service="viewer-web"

[http.routers.viewer-web-secure]
rule="PathPrefix(`/`)"
entryPoints="https-viewer"
middlewares=["viewer-gov-redirect"]
service="viewer-web"
[http.routers.viewer-web-secure.tls]

[http.routers.actor-web]
rule="PathPrefix(`/`)"
entryPoints="http-actor"
middlewares=["actor-web-https"]
service="actor-web"

[http.routers.actor-web-secure]
rule="PathPrefix(`/`)"
entryPoints="https-actor"
middlewares=["actor-gov-redirect"]
service="actor-web"
[http.routers.actor-web-secure.tls]

[http.services]
[http.services.actor-web.loadBalancer]
[[http.services.actor-web.loadBalancer.servers]]
url="http://actor-web"

[http.services.viewer-web.loadBalancer]
[[http.services.viewer-web.loadBalancer.servers]]
url="http://viewer-web"
