[api]
insecure=true

[accessLog]

[entryPoints]
[entryPoints.http-viewer]
address=":9001"
[entryPoints.https-viewer]
address=":9041"
[entryPoints.http-actor]
address=":9002"
[entryPoints.https-actor]
address=":9042"

[providers]
[providers.file]
filename="/etc/traefik/dynamic.toml"
watch=true
