graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [Use A Lasting Power of Attorney - Containers]
    style diagram fill:#ffffff,stroke:#ffffff

    2["<div style='font-weight: bold'>Attorney</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Attorney interacting with a<br />Lasting Power of Attorney.</div>"]
    style 2 fill:#08427b,stroke:#052e56,color:#ffffff
    3["<div style='font-weight: bold'>Donor</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Donor drafting the Lasting<br />Power of Attorney.</div>"]
    style 3 fill:#08427b,stroke:#052e56,color:#ffffff
    5["<div style='font-weight: bold'>Case Worker</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Case worker.</div>"]
    style 5 fill:#08427b,stroke:#052e56,color:#ffffff
    6["<div style='font-weight: bold'>Organisation</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Organisation or charity.</div>"]
    style 6 fill:#08427b,stroke:#052e56,color:#ffffff
    7("<div style='font-weight: bold'>LPA Case Management</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>PKA Sirius.</div>")
    style 7 fill:#999999,stroke:#6b6b6b,color:#ffffff

    subgraph 16 [Use A Lasting Power of Attorney]
      style 16 fill:#ffffff,stroke:#0b4884,color:#0b4884

      17[("<div style='font-weight: bold'>Application Database</div><div style='font-size: 70%; margin-top: 0px'>[Container: DynamoDB]</div><div style='font-size: 80%; margin-top:10px'>Stores generated code, user<br />accounts, Sirius LPA IDs, and<br />LPA/Actor codes.</div>")]
      style 17 fill:#438dd5,stroke:#2e6295,color:#ffffff
      18[("<div style='font-weight: bold'>AWS Cloudwatch</div><div style='font-size: 70%; margin-top: 0px'>[Container: AWS Cloudwatch]</div><div style='font-size: 80%; margin-top:10px'>Logging and observability.</div>")]
      style 18 fill:#438dd5,stroke:#2e6295,color:#ffffff
      19("<div style='font-weight: bold'>API Layer</div><div style='font-size: 70%; margin-top: 0px'>[Container: PHP]</div><div style='font-size: 80%; margin-top:10px'>Provides features to generate<br />sharing codes, and look up<br />LPA data from Sirius.</div>")
      style 19 fill:#438dd5,stroke:#2e6295,color:#ffffff
      25("<div style='font-weight: bold'>View an LPA Frontend</div><div style='font-size: 70%; margin-top: 0px'>[Container: PHP, CSS, JS, TWIG]</div><div style='font-size: 80%; margin-top:10px'>Provides features to view<br />LPAs shared by LPA Actors.</div>")
      style 25 fill:#438dd5,stroke:#2e6295,color:#ffffff
      27("<div style='font-weight: bold'>Use an LPA Frontend</div><div style='font-size: 70%; margin-top: 0px'>[Container: PHP, CSS, JS, TWIG]</div><div style='font-size: 80%; margin-top:10px'>Provides features to retrieve<br />LPAs and generate codes for<br />sharing LPAs.</div>")
      style 27 fill:#438dd5,stroke:#2e6295,color:#ffffff
      29("<div style='font-weight: bold'>Admin Application</div><div style='font-size: 70%; margin-top: 0px'>[Container: Go, CSS, JS, TWIG]</div><div style='font-size: 80%; margin-top:10px'>Provides search and stats<br />features for service team<br />users.</div>")
      style 29 fill:#438dd5,stroke:#2e6295,color:#ffffff
    end

    19-. "<div>Connects to</div><div style='font-size: 70%'></div>" .->17
    19-. "<div>Makes REST requests to</div><div style='font-size: 70%'></div>" .->7
    25-. "<div>Makes requests to</div><div style='font-size: 70%'></div>" .->19
    27-. "<div>Makes requests to</div><div style='font-size: 70%'></div>" .->19
    29-. "<div>Makes requests to</div><div style='font-size: 70%'></div>" .->17
    29-. "<div>Makes requests to</div><div style='font-size: 70%'></div>" .->18
    29-. "<div>Makes REST requests to</div><div style='font-size: 70%'></div>" .->7
    3-. "<div></div><div style='font-size: 70%'></div>" .->27
    2-. "<div></div><div style='font-size: 70%'></div>" .->27
    6-. "<div></div><div style='font-size: 70%'></div>" .->25
    5-. "<div></div><div style='font-size: 70%'></div>" .->29
  end
