// Code generated by mockery v2.51.0. DO NOT EDIT.

package mocks

import (
	context "context"

	events "github.com/aws/aws-lambda-go/events"
	mock "github.com/stretchr/testify/mock"
)

// CloudWatchHandler is an autogenerated mock type for the CloudWatchHandler type
type CloudWatchHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, event
func (_m *CloudWatchHandler) Handle(ctx context.Context, event events.CloudWatchEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, events.CloudWatchEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCloudWatchHandler creates a new instance of CloudWatchHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloudWatchHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *CloudWatchHandler {
	mock := &CloudWatchHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
