// Code generated by mockery v2.51.0. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	mock "github.com/stretchr/testify/mock"
)

// DynamodbClient is an autogenerated mock type for the DynamodbClient type
type DynamodbClient struct {
	mock.Mock
}

// ExistsLpaIDAndUserID provides a mock function with given fields: ctx, lpaId, userId
func (_m *DynamodbClient) ExistsLpaIDAndUserID(ctx context.Context, lpaId string, userId string) (bool, error) {
	ret := _m.Called(ctx, lpaId, userId)

	if len(ret) == 0 {
		panic("no return value specified for ExistsLpaIDAndUserID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, lpaId, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, lpaId, userId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, lpaId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OneByIdentity provides a mock function with given fields: ctx, uid, v
func (_m *DynamodbClient) OneByIdentity(ctx context.Context, uid string, v interface{}) error {
	ret := _m.Called(ctx, uid, v)

	if len(ret) == 0 {
		panic("no return value specified for OneByIdentity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, uid, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Put provides a mock function with given fields: ctx, tableName, item
func (_m *DynamodbClient) Put(ctx context.Context, tableName string, item map[string]types.AttributeValue) error {
	ret := _m.Called(ctx, tableName, item)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]types.AttributeValue) error); ok {
		r0 = rf(ctx, tableName, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDynamodbClient creates a new instance of DynamodbClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDynamodbClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *DynamodbClient {
	mock := &DynamodbClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
