// Code generated by mockery v2.51.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// factory is an autogenerated mock type for the factory type
type factory struct {
	mock.Mock
}

// newFactory creates a new instance of factory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *factory {
	mock := &factory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
