#!/usr/bin/env bash

# count LPAs added between the specified dates, by doing a DynamoDB scan and reducing this down todate unique SiriusUids so that we don't count LPAs twice when 
# added todate more than one account

get_lpas() {
    aws dynamodb scan \
      --table-name demo-UserLpaActorMap \
      --filter-expression "Added BETWEEN :fromdate AND :todate" \
      --expression-attribute-values "{ \":fromdate\" : { \"S\" : \"$fromdate\" }, \":todate\" : { \"S\" : \"$todate\" } }" \
      | jq '.Items[].SiriusUid.S' | sort | uniq | wc -l
}

# if less than 2 args supplied, then as a default, use today and a month ago as todate and fromdate 
if [ $# -lt 2 ]
then
    todate=$(date +"%Y-%m-%d")
# handle different date command on Mac and Linux
    if [ $(uname) == "Darwin" ] 
    then
        fromdate=$(date -v-1m +"%Y-%m-%d")
    else
        fromdate=$(date -d "1 month ago" +"%Y-%m-%d")
    fi
else
# if 2 args were supplied, we use these as fromdate and todate
    fromdate=$1
    todate=$2
fi
echo "LPAs added between $fromdate and $todate:"
get_lpas 

