#!/usr/bin/env bash

# count LPAs added between the specified dates, by doing a DynamoDB scan and reducing this down todate unique SiriusUids so that we don't count LPAs twice when
# added todate more than one account

get_lpas() {
    aws dynamodb scan \
      --table-name $environment-UserLpaActorMap \
      --filter-expression "Added BETWEEN :fromdate AND :todate" \
      --expression-attribute-values "{ \":fromdate\" : { \"S\" : \"$fromdate\" }, \":todate\" : { \"S\" : \"$todate\" } }" \
      | jq '.Items[].SiriusUid.S' | sort | uniq | wc -l
}

get_viewer_codes_created() {
    aws dynamodb scan \
      --table-name $environment-ViewerCodes \
      --filter-expression "Added BETWEEN :fromdate AND :todate" \
      --expression-attribute-values "{ \":fromdate\" : { \"S\" : \"$fromdate\" }, \":todate\" : { \"S\" : \"$todate\" } }" \
      | jq '.Items[].ViewerCode.S' | sort | wc -l
}

get_viewer_codes_viewed() {
    aws dynamodb scan \
      --table-name $environment-ViewerActivity \
      --filter-expression "Viewed BETWEEN :fromdate AND :todate" \
      --expression-attribute-values "{ \":fromdate\" : { \"S\" : \"$fromdate\" }, \":todate\" : { \"S\" : \"$todate\" } }" \
      | jq '.Items[].ViewerCode.S' | sort | wc -l
}

get_accounts_created() {
    aws cloudwatch get-metric-statistics \
      --namespace ${environment}_events \
      --metric-name account_created_event \
      --statistics Sum \
      --start-time "$fromdate" \
      --end-time "$todate" \
      --period 3600 \
      | jq 'reduce .["Datapoints"][].Sum as $item (0; . + $item)'
}

get_lpas_with_dups() {
    results=`aws dynamodb scan \
      --table-name $environment-UserLpaActorMap \
      --filter-expression "Added BETWEEN :fromdate AND :todate" \
      --expression-attribute-values "{ \":fromdate\" : { \"S\" : \"$fromdate\" }, \":todate\" : { \"S\" : \"$todate\" } }" \
      | jq '.Items[] | {SiriusUid, UserId}' | jq -j '.SiriusUid.S," ",.UserId.S,"\n"' | sort | uniq -d | awk '{print $1}' | sort | uniq`
    echo "$results"
    echo "$results" | wc -l
}

# if no args supplied, default to demo environment
if [ $# -lt 1 ]
then
    environment="demo"
else
    environment=$1
fi
# if less than 2 args supplied, then as a default, use today and a month ago as todate and fromdate
if [ $# -lt 3 ]
then
    todate=$(date +"%Y-%m-%d")
# handle different date command on Mac and Linux
    if [ $(uname) == "Darwin" ]
    then
        fromdate=$(date -v-1m +"%Y-%m-%d")
    else
        fromdate=$(date -d "1 month ago" +"%Y-%m-%d")
    fi
else
# if 3 args were supplied, we use 2cnd and 3rd as fromdate and todate
    fromdate=$2
    todate=$3
fi

echo "LPAs in $environment environment added between $fromdate and $todate:"
get_lpas
echo "Viewer codes created in $environment environment between $fromdate and $todate:"
get_viewer_codes_created
echo "Viewer codes viewed in $environment environment between $fromdate and $todate:"
get_viewer_codes_viewed
echo "Actor accounts created in $environment environment between $fromdate and $todate:"
get_accounts_created
get_lpas_with_dups
