#!/bin/bash

# count LPAs added between the specified dates, by doing a DynamoDB scan and reducing this down to unique SiriusUids so that we don't count LPAs twice when 
# added to more than one account

get_lpas() {
    aws-vault exec ual-dev -- aws dynamodb scan \
      --table-name demo-UserLpaActorMap \
      --filter-expression "Added BETWEEN :from AND :to" \
      --expression-attribute-values "{ \":from\" : { \"S\" : \"$1\" }, \":to\" : { \"S\" : \"$2\" } }" \
      | jq '.Items[].SiriusUid.S' | sort | uniq | wc -l
}

get_lpas 2019-01-01 2020-07-07

