<?php $this->layout('layout::default', ['title' => 'Enter code']) ?>

<div class="govuk-width-container">
    <div class="govuk-phase-banner">
        <p class="govuk-phase-banner__content"><strong class="govuk-tag govuk-phase-banner__content__tag ">
                alpha
            </strong>
            <span class="govuk-phase-banner__text">
                    This is a new service – your
                    <a class="govuk-link" href="#">feedback</a> will help us to improve it.
                </span>
        </p>
    </div>
    <a href="/" class="govuk-back-link">Back</a>

    <main class="govuk-main-wrapper">
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-one-half">
                <h1 class="govuk-heading-xl">Enter Code</h1>

                <form method="post">
                    <fieldset class="govuk-fieldset">

                        <div class="govuk-form-group">
                            <label class="govuk-label" for="share-code">
                                Share code
                            </label>
                            <input class="govuk-input" id="share-code" name="share-code" type="text">
                        </div>

                        <details class="govuk-details">
                            <summary class="govuk-details__summary">
                                    <span class="govuk-details__summary-text">
                                        What is a share code?
                                    </span>
                            </summary>
                            <div class="govuk-details__text">
                                A share code is given to you by the donor or an attorney named on the lasting power
                                of attorney.
                            </div>
                        </details>

                        <button type="submit" class="govuk-button">Save and continue</button>
                    </fieldset>
                </form>
            </div>
        </div>

    </main>
</div>
