<?php $this->layout('layout::default', ['title' => 'Enter code']) ?>

<div class="govuk-width-container">
    <div class="govuk-phase-banner">
        <p class="govuk-phase-banner__content"><strong class="govuk-tag govuk-phase-banner__content__tag ">
                alpha
            </strong>
            <span class="govuk-phase-banner__text">
                    This is a new service – your
                    <a class="govuk-link" href="#">feedback</a> will help us to improve it.
                </span>
        </p>
    </div>

    <main class="govuk-main-wrapper">
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-one-half">
                <h1 class="govuk-heading-xl">Use your LPA Homepage</h1>


                <a href="/enter-code" role="button" draggable="false" class="govuk-button govuk-button--start">
                    Start now
                </a>

            </div>
        </div>

    </main>
</div>
