version: "2"
linters:
  enable:
    - err113
    - paralleltest
    - staticcheck
    - wsl
  settings:
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # False positive: https://github.com/kunwardeep/paralleltest/issues/8.
      - linters:
          - paralleltest
        text: does not use range value in test Run
      - linters:
          # Making up exceptions in test files is fine (unless)
          - err113
        path: _test\.go
        text: do not define dynamic errors, use wrapped static errors instead
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
