// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dynamo

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	mock "github.com/stretchr/testify/mock"
)

// newMockDynamoDB creates a new instance of mockDynamoDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDynamoDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDynamoDB {
	mock := &mockDynamoDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockDynamoDB is an autogenerated mock type for the DynamoDB type
type mockDynamoDB struct {
	mock.Mock
}

type mockDynamoDB_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDynamoDB) EXPECT() *mockDynamoDB_Expecter {
	return &mockDynamoDB_Expecter{mock: &_m.Mock}
}

// GetItem provides a mock function for the type mockDynamoDB
func (_mock *mockDynamoDB) GetItem(context1 context.Context, getItemInput *dynamodb.GetItemInput, fns ...func(*dynamodb.Options)) (*dynamodb.GetItemOutput, error) {
	// func(*dynamodb.Options)
	_va := make([]interface{}, len(fns))
	for _i := range fns {
		_va[_i] = fns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, context1, getItemInput)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 *dynamodb.GetItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.GetItemInput, ...func(*dynamodb.Options)) (*dynamodb.GetItemOutput, error)); ok {
		return returnFunc(context1, getItemInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.GetItemInput, ...func(*dynamodb.Options)) *dynamodb.GetItemOutput); ok {
		r0 = returnFunc(context1, getItemInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.GetItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.GetItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(context1, getItemInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDynamoDB_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type mockDynamoDB_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - context1 context.Context
//   - getItemInput *dynamodb.GetItemInput
//   - fns ...func(*dynamodb.Options)
func (_e *mockDynamoDB_Expecter) GetItem(context1 interface{}, getItemInput interface{}, fns ...interface{}) *mockDynamoDB_GetItem_Call {
	return &mockDynamoDB_GetItem_Call{Call: _e.mock.On("GetItem",
		append([]interface{}{context1, getItemInput}, fns...)...)}
}

func (_c *mockDynamoDB_GetItem_Call) Run(run func(context1 context.Context, getItemInput *dynamodb.GetItemInput, fns ...func(*dynamodb.Options))) *mockDynamoDB_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.GetItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.GetItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		variadicArgs := make([]func(*dynamodb.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*dynamodb.Options))
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockDynamoDB_GetItem_Call) Return(getItemOutput *dynamodb.GetItemOutput, err error) *mockDynamoDB_GetItem_Call {
	_c.Call.Return(getItemOutput, err)
	return _c
}

func (_c *mockDynamoDB_GetItem_Call) RunAndReturn(run func(context1 context.Context, getItemInput *dynamodb.GetItemInput, fns ...func(*dynamodb.Options)) (*dynamodb.GetItemOutput, error)) *mockDynamoDB_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// PutItem provides a mock function for the type mockDynamoDB
func (_mock *mockDynamoDB) PutItem(context1 context.Context, putItemInput *dynamodb.PutItemInput, fns ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error) {
	// func(*dynamodb.Options)
	_va := make([]interface{}, len(fns))
	for _i := range fns {
		_va[_i] = fns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, context1, putItemInput)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutItem")
	}

	var r0 *dynamodb.PutItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.PutItemInput, ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error)); ok {
		return returnFunc(context1, putItemInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.PutItemInput, ...func(*dynamodb.Options)) *dynamodb.PutItemOutput); ok {
		r0 = returnFunc(context1, putItemInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.PutItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.PutItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(context1, putItemInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDynamoDB_PutItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutItem'
type mockDynamoDB_PutItem_Call struct {
	*mock.Call
}

// PutItem is a helper method to define mock.On call
//   - context1 context.Context
//   - putItemInput *dynamodb.PutItemInput
//   - fns ...func(*dynamodb.Options)
func (_e *mockDynamoDB_Expecter) PutItem(context1 interface{}, putItemInput interface{}, fns ...interface{}) *mockDynamoDB_PutItem_Call {
	return &mockDynamoDB_PutItem_Call{Call: _e.mock.On("PutItem",
		append([]interface{}{context1, putItemInput}, fns...)...)}
}

func (_c *mockDynamoDB_PutItem_Call) Run(run func(context1 context.Context, putItemInput *dynamodb.PutItemInput, fns ...func(*dynamodb.Options))) *mockDynamoDB_PutItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.PutItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.PutItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		variadicArgs := make([]func(*dynamodb.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*dynamodb.Options))
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockDynamoDB_PutItem_Call) Return(putItemOutput *dynamodb.PutItemOutput, err error) *mockDynamoDB_PutItem_Call {
	_c.Call.Return(putItemOutput, err)
	return _c
}

func (_c *mockDynamoDB_PutItem_Call) RunAndReturn(run func(context1 context.Context, putItemInput *dynamodb.PutItemInput, fns ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error)) *mockDynamoDB_PutItem_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type mockDynamoDB
func (_mock *mockDynamoDB) Query(context1 context.Context, queryInput *dynamodb.QueryInput, fns ...func(*dynamodb.Options)) (*dynamodb.QueryOutput, error) {
	// func(*dynamodb.Options)
	_va := make([]interface{}, len(fns))
	for _i := range fns {
		_va[_i] = fns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, context1, queryInput)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *dynamodb.QueryOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) (*dynamodb.QueryOutput, error)); ok {
		return returnFunc(context1, queryInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) *dynamodb.QueryOutput); ok {
		r0 = returnFunc(context1, queryInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.QueryOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(context1, queryInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDynamoDB_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type mockDynamoDB_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - context1 context.Context
//   - queryInput *dynamodb.QueryInput
//   - fns ...func(*dynamodb.Options)
func (_e *mockDynamoDB_Expecter) Query(context1 interface{}, queryInput interface{}, fns ...interface{}) *mockDynamoDB_Query_Call {
	return &mockDynamoDB_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{context1, queryInput}, fns...)...)}
}

func (_c *mockDynamoDB_Query_Call) Run(run func(context1 context.Context, queryInput *dynamodb.QueryInput, fns ...func(*dynamodb.Options))) *mockDynamoDB_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.QueryInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.QueryInput)
		}
		var arg2 []func(*dynamodb.Options)
		variadicArgs := make([]func(*dynamodb.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*dynamodb.Options))
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockDynamoDB_Query_Call) Return(queryOutput *dynamodb.QueryOutput, err error) *mockDynamoDB_Query_Call {
	_c.Call.Return(queryOutput, err)
	return _c
}

func (_c *mockDynamoDB_Query_Call) RunAndReturn(run func(context1 context.Context, queryInput *dynamodb.QueryInput, fns ...func(*dynamodb.Options)) (*dynamodb.QueryOutput, error)) *mockDynamoDB_Query_Call {
	_c.Call.Return(run)
	return _c
}

// TransactWriteItems provides a mock function for the type mockDynamoDB
func (_mock *mockDynamoDB) TransactWriteItems(ctx context.Context, params *dynamodb.TransactWriteItemsInput, optFns ...func(*dynamodb.Options)) (*dynamodb.TransactWriteItemsOutput, error) {
	// func(*dynamodb.Options)
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for TransactWriteItems")
	}

	var r0 *dynamodb.TransactWriteItemsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.TransactWriteItemsInput, ...func(*dynamodb.Options)) (*dynamodb.TransactWriteItemsOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.TransactWriteItemsInput, ...func(*dynamodb.Options)) *dynamodb.TransactWriteItemsOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.TransactWriteItemsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.TransactWriteItemsInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDynamoDB_TransactWriteItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactWriteItems'
type mockDynamoDB_TransactWriteItems_Call struct {
	*mock.Call
}

// TransactWriteItems is a helper method to define mock.On call
//   - ctx context.Context
//   - params *dynamodb.TransactWriteItemsInput
//   - optFns ...func(*dynamodb.Options)
func (_e *mockDynamoDB_Expecter) TransactWriteItems(ctx interface{}, params interface{}, optFns ...interface{}) *mockDynamoDB_TransactWriteItems_Call {
	return &mockDynamoDB_TransactWriteItems_Call{Call: _e.mock.On("TransactWriteItems",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *mockDynamoDB_TransactWriteItems_Call) Run(run func(ctx context.Context, params *dynamodb.TransactWriteItemsInput, optFns ...func(*dynamodb.Options))) *mockDynamoDB_TransactWriteItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.TransactWriteItemsInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.TransactWriteItemsInput)
		}
		var arg2 []func(*dynamodb.Options)
		variadicArgs := make([]func(*dynamodb.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*dynamodb.Options))
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockDynamoDB_TransactWriteItems_Call) Return(transactWriteItemsOutput *dynamodb.TransactWriteItemsOutput, err error) *mockDynamoDB_TransactWriteItems_Call {
	_c.Call.Return(transactWriteItemsOutput, err)
	return _c
}

func (_c *mockDynamoDB_TransactWriteItems_Call) RunAndReturn(run func(ctx context.Context, params *dynamodb.TransactWriteItemsInput, optFns ...func(*dynamodb.Options)) (*dynamodb.TransactWriteItemsOutput, error)) *mockDynamoDB_TransactWriteItems_Call {
	_c.Call.Return(run)
	return _c
}
