[www]
; https://www.php.net/manual/en/install.fpm.configuration.php#access-format
;
; JSON logging
;  {
;    "time": "2019-06-12T20:26:01+00:00",
;    "level": "INFO",
;    "service_name": "api-web",
;    "request": {
;      "method": "GET",
;      "path": "/",
;      "protocol": "HTTP/1.1",
;      "time": "0.012",
;      "memory": "4",
;      "referrer": "-",
;      "user_agent": "GuzzleHttp/7"
;    },
;    "client_ip": "2.28.107.100",
;    "remote_addr": "172.22.0.3",
;    "status": "200",
;    "trace_id": "Root=1-e29b1539-aab72db44f8188dacdd196aa;Parent=38c15ce40c9d39d0;Sampled=1"
;  }
access.format = '{"time":"%{%Y-%m-%dT%H:%M:%S%z}T","level":"INFO","service_name":"api-web","request":{"method":"%m","path":"%{REQUEST_URI}e","protocol":"%{SERVER_PROTOCOL}e","time":"%d","memory":"%{mega}M","referrer":"%{HTTP_REFERER}e","user_agent":"%{HTTP_USER_AGENT}e"},"client_ip":"%{HTTP_X_FORWARDED_FOR}e","remote_addr":"%R","status":"%s","trace_id":"%{HTTP_X_AMZN_TRACE_ID}e"}'
ping.path = /ping

pm = static
pm.max_children = ${OPG_PHP_POOL_CHILDREN_MAX}
pm.status_path = /status
; Create a new pool for the status page to avoid adding overhead to the main pool
pm.status_listen = 127.0.0.1:9001
