vulnerabilities:
  - id: CVE-2026-0861
    expired_at: 2026-04-16
    statement: >
      https://security-tracker.debian.org/tracker/CVE-2026-0861 rates this as a minor issue for debian Trixie and
      is consequently wontfix until the next major release.
