vulnerabilities:
  - id: CVE-2025-49796
    statement: Testing ignore file for know CVE in this image
    expired_at: 2025-08-02
  - id: CVE-2025-49794
    statement: Testing ignore file for know CVE in this image
    expired_at: 2025-08-02
  - id: CVE-2025-49795
    statement: Testing ignore file for know CVE in this image
    expired_at: 2025-08-02
