// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package main

import (
	"context"
	"time"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	mock "github.com/stretchr/testify/mock"
)

// newMockFactory creates a new instance of mockFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockFactory {
	mock := &mockFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockFactory is an autogenerated mock type for the Factory type
type mockFactory struct {
	mock.Mock
}

type mockFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *mockFactory) EXPECT() *mockFactory_Expecter {
	return &mockFactory_Expecter{mock: &_m.Mock}
}

// DynamoClient provides a mock function for the type mockFactory
func (_mock *mockFactory) DynamoClient() DynamodbClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DynamoClient")
	}

	var r0 DynamodbClient
	if returnFunc, ok := ret.Get(0).(func() DynamodbClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(DynamodbClient)
		}
	}
	return r0
}

// mockFactory_DynamoClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DynamoClient'
type mockFactory_DynamoClient_Call struct {
	*mock.Call
}

// DynamoClient is a helper method to define mock.On call
func (_e *mockFactory_Expecter) DynamoClient() *mockFactory_DynamoClient_Call {
	return &mockFactory_DynamoClient_Call{Call: _e.mock.On("DynamoClient")}
}

func (_c *mockFactory_DynamoClient_Call) Run(run func()) *mockFactory_DynamoClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockFactory_DynamoClient_Call) Return(dynamodbClient DynamodbClient) *mockFactory_DynamoClient_Call {
	_c.Call.Return(dynamodbClient)
	return _c
}

func (_c *mockFactory_DynamoClient_Call) RunAndReturn(run func() DynamodbClient) *mockFactory_DynamoClient_Call {
	_c.Call.Return(run)
	return _c
}

// Now provides a mock function for the type mockFactory
func (_mock *mockFactory) Now() func() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 func() time.Time
	if returnFunc, ok := ret.Get(0).(func() func() time.Time); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func() time.Time)
		}
	}
	return r0
}

// mockFactory_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type mockFactory_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *mockFactory_Expecter) Now() *mockFactory_Now_Call {
	return &mockFactory_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *mockFactory_Now_Call) Run(run func()) *mockFactory_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockFactory_Now_Call) Return(fn func() time.Time) *mockFactory_Now_Call {
	_c.Call.Return(fn)
	return _c
}

func (_c *mockFactory_Now_Call) RunAndReturn(run func() func() time.Time) *mockFactory_Now_Call {
	_c.Call.Return(run)
	return _c
}

// UuidString provides a mock function for the type mockFactory
func (_mock *mockFactory) UuidString() func() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UuidString")
	}

	var r0 func() string
	if returnFunc, ok := ret.Get(0).(func() func() string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func() string)
		}
	}
	return r0
}

// mockFactory_UuidString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UuidString'
type mockFactory_UuidString_Call struct {
	*mock.Call
}

// UuidString is a helper method to define mock.On call
func (_e *mockFactory_Expecter) UuidString() *mockFactory_UuidString_Call {
	return &mockFactory_UuidString_Call{Call: _e.mock.On("UuidString")}
}

func (_c *mockFactory_UuidString_Call) Run(run func()) *mockFactory_UuidString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockFactory_UuidString_Call) Return(fn func() string) *mockFactory_UuidString_Call {
	_c.Call.Return(fn)
	return _c
}

func (_c *mockFactory_UuidString_Call) RunAndReturn(run func() func() string) *mockFactory_UuidString_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDynamodbClient creates a new instance of mockDynamodbClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDynamodbClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDynamodbClient {
	mock := &mockDynamodbClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockDynamodbClient is an autogenerated mock type for the DynamodbClient type
type mockDynamodbClient struct {
	mock.Mock
}

type mockDynamodbClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDynamodbClient) EXPECT() *mockDynamodbClient_Expecter {
	return &mockDynamodbClient_Expecter{mock: &_m.Mock}
}

// ExistsLpaIDAndUserID provides a mock function for the type mockDynamodbClient
func (_mock *mockDynamodbClient) ExistsLpaIDAndUserID(ctx context.Context, lpaUID string, userID string) (bool, error) {
	ret := _mock.Called(ctx, lpaUID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsLpaIDAndUserID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, lpaUID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, lpaUID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, lpaUID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDynamodbClient_ExistsLpaIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsLpaIDAndUserID'
type mockDynamodbClient_ExistsLpaIDAndUserID_Call struct {
	*mock.Call
}

// ExistsLpaIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - lpaUID string
//   - userID string
func (_e *mockDynamodbClient_Expecter) ExistsLpaIDAndUserID(ctx interface{}, lpaUID interface{}, userID interface{}) *mockDynamodbClient_ExistsLpaIDAndUserID_Call {
	return &mockDynamodbClient_ExistsLpaIDAndUserID_Call{Call: _e.mock.On("ExistsLpaIDAndUserID", ctx, lpaUID, userID)}
}

func (_c *mockDynamodbClient_ExistsLpaIDAndUserID_Call) Run(run func(ctx context.Context, lpaUID string, userID string)) *mockDynamodbClient_ExistsLpaIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockDynamodbClient_ExistsLpaIDAndUserID_Call) Return(b bool, err error) *mockDynamodbClient_ExistsLpaIDAndUserID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockDynamodbClient_ExistsLpaIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, lpaUID string, userID string) (bool, error)) *mockDynamodbClient_ExistsLpaIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// OneByIdentity provides a mock function for the type mockDynamodbClient
func (_mock *mockDynamodbClient) OneByIdentity(ctx context.Context, uid string, v any) error {
	ret := _mock.Called(ctx, uid, v)

	if len(ret) == 0 {
		panic("no return value specified for OneByIdentity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, uid, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockDynamodbClient_OneByIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OneByIdentity'
type mockDynamodbClient_OneByIdentity_Call struct {
	*mock.Call
}

// OneByIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
//   - v any
func (_e *mockDynamodbClient_Expecter) OneByIdentity(ctx interface{}, uid interface{}, v interface{}) *mockDynamodbClient_OneByIdentity_Call {
	return &mockDynamodbClient_OneByIdentity_Call{Call: _e.mock.On("OneByIdentity", ctx, uid, v)}
}

func (_c *mockDynamodbClient_OneByIdentity_Call) Run(run func(ctx context.Context, uid string, v any)) *mockDynamodbClient_OneByIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockDynamodbClient_OneByIdentity_Call) Return(err error) *mockDynamodbClient_OneByIdentity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockDynamodbClient_OneByIdentity_Call) RunAndReturn(run func(ctx context.Context, uid string, v any) error) *mockDynamodbClient_OneByIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type mockDynamodbClient
func (_mock *mockDynamodbClient) Put(ctx context.Context, tableName string, item map[string]types.AttributeValue) error {
	ret := _mock.Called(ctx, tableName, item)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]types.AttributeValue) error); ok {
		r0 = returnFunc(ctx, tableName, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockDynamodbClient_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type mockDynamodbClient_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - tableName string
//   - item map[string]types.AttributeValue
func (_e *mockDynamodbClient_Expecter) Put(ctx interface{}, tableName interface{}, item interface{}) *mockDynamodbClient_Put_Call {
	return &mockDynamodbClient_Put_Call{Call: _e.mock.On("Put", ctx, tableName, item)}
}

func (_c *mockDynamodbClient_Put_Call) Run(run func(ctx context.Context, tableName string, item map[string]types.AttributeValue)) *mockDynamodbClient_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]types.AttributeValue
		if args[2] != nil {
			arg2 = args[2].(map[string]types.AttributeValue)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockDynamodbClient_Put_Call) Return(err error) *mockDynamodbClient_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockDynamodbClient_Put_Call) RunAndReturn(run func(ctx context.Context, tableName string, item map[string]types.AttributeValue) error) *mockDynamodbClient_Put_Call {
	_c.Call.Return(run)
	return _c
}

// newMockHandler creates a new instance of mockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockHandler {
	mock := &mockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockHandler is an autogenerated mock type for the Handler type
type mockHandler struct {
	mock.Mock
}

type mockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockHandler) EXPECT() *mockHandler_Expecter {
	return &mockHandler_Expecter{mock: &_m.Mock}
}

// EventHandler provides a mock function for the type mockHandler
func (_mock *mockHandler) EventHandler(context1 context.Context, factory Factory, cloudWatchEvent *events.CloudWatchEvent) error {
	ret := _mock.Called(context1, factory, cloudWatchEvent)

	if len(ret) == 0 {
		panic("no return value specified for EventHandler")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Factory, *events.CloudWatchEvent) error); ok {
		r0 = returnFunc(context1, factory, cloudWatchEvent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockHandler_EventHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventHandler'
type mockHandler_EventHandler_Call struct {
	*mock.Call
}

// EventHandler is a helper method to define mock.On call
//   - context1 context.Context
//   - factory Factory
//   - cloudWatchEvent *events.CloudWatchEvent
func (_e *mockHandler_Expecter) EventHandler(context1 interface{}, factory interface{}, cloudWatchEvent interface{}) *mockHandler_EventHandler_Call {
	return &mockHandler_EventHandler_Call{Call: _e.mock.On("EventHandler", context1, factory, cloudWatchEvent)}
}

func (_c *mockHandler_EventHandler_Call) Run(run func(context1 context.Context, factory Factory, cloudWatchEvent *events.CloudWatchEvent)) *mockHandler_EventHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Factory
		if args[1] != nil {
			arg1 = args[1].(Factory)
		}
		var arg2 *events.CloudWatchEvent
		if args[2] != nil {
			arg2 = args[2].(*events.CloudWatchEvent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockHandler_EventHandler_Call) Return(err error) *mockHandler_EventHandler_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockHandler_EventHandler_Call) RunAndReturn(run func(context1 context.Context, factory Factory, cloudWatchEvent *events.CloudWatchEvent) error) *mockHandler_EventHandler_Call {
	_c.Call.Return(run)
	return _c
}
