name: "[Lighthouse] Run Lighthouse CI"

defaults:
  run:
    shell: bash

on:
  workflow_call:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get PR URLs
        id: get_pr_urls
        run: |
          viewer_fqdn=$(cat ./terraform/environment/cluster_config.json | jq .viewer_fqdn | xargs)
          actor_fqdn=$(cat ./terraform/environment/cluster_config.json | jq .actor_fqdn | xargs)
          echo "{viewer_fqdn}={viewer_fqdn}" >> $GITHUB_OUTPUT
          echo "{actor_fqdn}={actor_fqdn}" >> $GITHUB_OUTPUT
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://${{ steps.get_pr_urls.outputs.viewer_fqdn }}
            https://${{ steps.get_pr_urls.outputs.actor_fqdn }}
          budgetPath: ./service-front/web/src/budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
