name: "[Docker] Node build web"

defaults:
  run:
    shell: bash

on:
  workflow_call:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: '.nvmrc'
      - name: cache node modules
        id: cache-npm
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        env:
          cache-name: cache-node-modules
        with:
          path: ./service-front/web/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/service-front/web/package-lock.json') }}
      - name: install dependencies
        run: |
          if [ ! -d service-front/web/node_modules ]; then
            docker compose run --rm npm ci --ignore-scripts
          fi
      - name: build assets
        run: |
          docker compose run --rm --volume $(pwd)/service-front/web/dist:/web/dist npm run build
      - name: archive dist
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: dist-web
          path: service-front/web/dist/
