name: "Documentation Update"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      branch_name:
        description: "The name of the branch doing the build"
        required: true
        type: string
      specific_path:
        description: "Run workflow only if path includes docs"
        required: true
        default: 'all'
        type: string

jobs:
  update_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v3
    