name: "PHP Linting with Code Sniffer"

on: workflow_call

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  phpcs:
    name: Lint PHP
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lint:
          - name: front
            image: front-app
            directory: service-front/app
          - name: api
            image: api-app
            directory: service-api/app
    env:
      IMAGE: ${{ matrix.lint.image }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        fetch-depth: 0

    - name: Detect changed PHP files
      run: |
        {
          echo "CHANGED_PHP_FILES<<EOF"
          git diff --name-only origin/main... -- '${{ matrix.lint.directory }}/**/*.php' | sed "s|^${{ matrix.lint.directory }}/||g"
          echo "EOF"
        } >> "$GITHUB_ENV"

    - name: Download Docker Image
      if: env.CHANGED_PHP_FILES != ''
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        name: ${{ matrix.lint.image }}-test
        path: /tmp/images
    - name: Load Image
      if: env.CHANGED_PHP_FILES != ''
      run: docker load -i /tmp/images/image.tar

    - name: Run phpcs
      id: phpcs
      if: env.CHANGED_PHP_FILES != ''
      run: |
        docker run --rm --volume ./output:/tmp/output $IMAGE:latest \
        vendor/bin/phpcs --standard=phpcs.xml.dist --report=full --report-xml=/tmp/output/phpcs-report.xml \
        $CHANGED_PHP_FILES

    - name: Publish PHPCS as PR annotations
      if: ${{ always() && steps.phpcs.outcome == 'failure' }}
      run: |
        echo "::add-matcher::.github/phpcs-problem-matcher.json"
        more ./output/phpcs-report.xml | sed "s|file name=\"|file name=\"${{ matrix.lint.directory }}/|g"
