name: "[Workflow] PR Environment"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

defaults:
  run:
    shell: bash

on:
  pull_request:

permissions:
  contents: write
  security-events: write
  pull-requests: read
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none
  id-token: write

jobs:
  cleanup_pr_workspaces:
    name: cleanup pr workspaces
    uses: ./.github/workflows/scheduled-workspace-cleanup.yml
    secrets:
      AWS_ACCESS_KEY_ID_ACTIONS: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      AWS_SECRET_ACCESS_KEY_ACTIONS: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
      USE_AN_LPA_DEPLOY_KEY_PRIVATE_KEY: ${{ secrets.USE_AN_LPA_DEPLOY_KEY_PRIVATE_KEY }}

  workflow_variables:
    runs-on: ubuntu-latest
    name: output workflow variables
    outputs:
      safe_branch_name: ${{ steps.safe_branch_name.outputs.safe }}
      short_sha: ${{ steps.variables.outputs.short_sha }}
      specific_path: ${{ steps.variables.outputs.path }}
      workspace_name: ${{ steps.set_workspace_name.outputs.workspace_name }}
      detect_app_code_changes: ${{ steps.changed-files-app.outputs.any_changed }}

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 2

      - name: Set safe branch name
        id: safe_branch_name
        uses: ministryofjustice/opg-github-actions/.github/actions/branch-name@ea1e81f43e7593acd74cc114085930f5f54914a2 # v3.1.7

      - name: get changed files in the admin folder
        id: changed-files-admin
        uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # 47.0.1
        with:
          files: |
            service-admin/**

      - name: get changed files in app code
        id: changed-files-app
        uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # 47.0.1
        with:
          files: |
            service-admin/**
            lambda-functions/**
            service-front/**
            service-api/**
            .github/workflows/_build-and-push.yml

      - name: get changed files in the terraform folder
        id: changed-files-terraform
        uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # 47.0.1
        with:
          files: |
            terraform/**

      - name: get changed docs files in any folder
        id: changed-files-docs
        uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # 47.0.1
        with:
          files: |
            **/*.md

      - name: extract variables for workflow
        id: variables
        run: |
          echo "short_sha=$(echo ${GITHUB_SHA:0:7})" >> $GITHUB_OUTPUT
          if [[ ${{ steps.changed-files-terraform.outputs.only_changed }} = "true" ]]
          then
            echo "path=$(echo terraform)" >> $GITHUB_OUTPUT
          elif [[ ${{ steps.changed-files-admin.outputs.only_changed }} = "true" ]]
          then
            echo "path=$(echo admin)" >> $GITHUB_OUTPUT
          elif [[ ${{ steps.changed-files-docs.outputs.only_changed }} = "true" ]]
          then
            echo "path=$(echo docs)" >> $GITHUB_OUTPUT
          else
            echo "path=$(echo all)" >> $GITHUB_OUTPUT
          fi

      - name: show specific path
        env:
          SPECIFIC_PATH: ${{ steps.variables.outputs.path }}
        run: |
          echo "path chosen - $SPECIFIC_PATH"

      - name: Set workspace name
        id: set_workspace_name
        run: |
          echo "workspace_name=${{ github.event.number }}${{ steps.safe_branch_name.outputs.safe }}" >> $GITHUB_OUTPUT

  update_documentation:
    name: update documentation
    runs-on: ubuntu-latest
    needs:
      - workflow_variables
    steps:
      - name: only update documentation
        run: echo 'Only docs have changed - skipping rest of pipeline'
    if: |
      needs.workflow_variables.outputs.specific_path == 'docs'

  terraform_lint:
    name: lint terraform code
    uses: ./.github/workflows/_lint-terraform.yml
    needs:
      - workflow_variables
    with:
      oidc_terraform_role: ${{ vars.OIDC_TERRAFORM_ROLE_DEVELOPMENT }}
      workspace: ${{ needs.workflow_variables.outputs.workspace_name }}
    secrets:
      USE_AN_LPA_DEPLOY_KEY_PRIVATE_KEY: ${{ secrets.USE_AN_LPA_DEPLOY_KEY_PRIVATE_KEY }}
    if: |
      needs.workflow_variables.outputs.specific_path != 'docs'

  node_test:
    name: test node dependencies
    uses: ./.github/workflows/_node-test.yml
    needs:
      - workflow_variables
    if: |
      needs.workflow_variables.outputs.specific_path == 'all'

  node_build:
    name: build node dependencies
    uses: ./.github/workflows/_node-build.yml
    needs:
      - workflow_variables
    if: |
      needs.workflow_variables.outputs.specific_path == 'all'

  resolve_docker_tag:
    name: resolve docker tag
    uses: ./.github/workflows/_tags-job.yml
    needs:
      - workflow_variables
    with:
      workspace_name: ${{ needs.workflow_variables.outputs.workspace_name }}
      safe_branch_name: ${{ needs.workflow_variables.outputs.safe_branch_name }}
      short_sha: ${{ needs.workflow_variables.outputs.short_sha }}
      detect_app_code_changes: ${{ needs.workflow_variables.outputs.detect_app_code_changes }}
    secrets:
      AWS_ACCESS_KEY_ID_ACTIONS: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      AWS_SECRET_ACCESS_KEY_ACTIONS: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}

  docker_build_scan_push:
    name: build, test, scan and push
    uses: ./.github/workflows/_build-and-push.yml
    needs:
      - workflow_variables
      - node_test
      - node_build
      - resolve_docker_tag
    with:
      tag: ${{ needs.resolve_docker_tag.outputs.docker_tag }}
      branch_name: ${{ needs.workflow_variables.outputs.safe_branch_name }}
      push_to_ecr: true
      specific_path: ${{ needs.workflow_variables.outputs.specific_path }}
      oidc_docker_role: ${{ vars.OIDC_DOCKER_ROLE }}
    if: |
      always() &&
      needs.workflow_variables.outputs.detect_app_code_changes == 'true' &&
      (needs.node_test.result == 'success' || needs.node_test.result == 'skipped') &&
      (needs.node_build.result == 'success' || needs.node_build.result == 'skipped') &&
      needs.workflow_variables.result == 'success' &&
      needs.resolve_docker_tag.result == 'success'

  pact_upload:
    name: upload contracts to pact
    uses: ./.github/workflows/_pact-upload.yml
    needs:
      - docker_build_scan_push
      - workflow_variables
      - resolve_docker_tag
    with:
      specific_path: ${{ needs.workflow_variables.outputs.specific_path }}
      tag: ${{ needs.resolve_docker_tag.outputs.docker_tag }}
      branch: ${{ needs.workflow_variables.outputs.safe_branch_name }}
      commit_sha: ${{ github.event.pull_request.head.sha }}
    secrets:
      PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
    if: |
      always() &&
      needs.docker_build_scan_push.result == 'success'

  code_coverage:
    name: upload to code coverage
    uses: ./.github/workflows/_codecov.yml
    needs:
      - docker_build_scan_push
      - workflow_variables
    with:
      specific_path: ${{ needs.workflow_variables.outputs.specific_path }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    if: |
      always() &&
      ( needs.docker_build_scan_push.result == 'success' || needs.docker_build_scan_push.result == 'failure' )

  terraform_apply_shared_development:
    name: terraform apply shared development
    uses: ./.github/workflows/_run-terraform.yml
    needs:
      - terraform_lint
      - workflow_variables
    with:
      apply: false
      oidc_terraform_role: ${{ vars.OIDC_TERRAFORM_ROLE_DEVELOPMENT }}
      oidc_pagerduty_token_role: ${{ vars.OIDC_PAGERDUTY_TOKEN_ROLE }}
      specific_path: ${{ needs.workflow_variables.outputs.specific_path }}
      terraform_path: account
      workspace: development
    secrets:
      USE_AN_LPA_DEPLOY_KEY_PRIVATE_KEY: ${{ secrets.USE_AN_LPA_DEPLOY_KEY_PRIVATE_KEY }}

  terraform_apply_environment:
    name: terraform apply environment
    uses: ./.github/workflows/_run-terraform.yml
    needs:
      - docker_build_scan_push
      - resolve_docker_tag
      - terraform_lint
      - workflow_variables
    with:
      add_ttl: true
      apply: true
      container_version: ${{ needs.resolve_docker_tag.outputs.docker_tag }}
      oidc_terraform_role: ${{ vars.OIDC_TERRAFORM_ROLE_DEVELOPMENT }}
      oidc_pagerduty_token_role: ${{ vars.OIDC_PAGERDUTY_TOKEN_ROLE }}
      specific_path: ${{ needs.workflow_variables.outputs.specific_path }}
      terraform_path: environment
      workspace: ${{ needs.workflow_variables.outputs.workspace_name }}
    secrets:
      USE_AN_LPA_DEPLOY_KEY_PRIVATE_KEY: ${{ secrets.USE_AN_LPA_DEPLOY_KEY_PRIVATE_KEY }}

    if: |
      always() &&
      needs.terraform_lint.result == 'success' &&
      (needs.docker_build_scan_push.result == 'success' || needs.workflow_variables.outputs.detect_app_code_changes == 'false') &&
      needs.workflow_variables.result == 'success' &&
      needs.resolve_docker_tag.result == 'success'

  seed_dynamodb:
    name: seed dynamodb
    uses: ./.github/workflows/_seed-database.yml
    needs:
      - terraform_apply_environment
      - terraform_apply_shared_development
      - workflow_variables
    with:
      workspace: ${{ needs.workflow_variables.outputs.workspace_name }}
    secrets:
      AWS_ACCESS_KEY_ID_ACTIONS: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      AWS_SECRET_ACCESS_KEY_ACTIONS: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
    if: |
      always() &&
      needs.terraform_apply_environment.result == 'success' &&
      needs.terraform_apply_shared_development.result == 'success'

  run_behat_suite:
    name: run behat tests against environment
    uses: ./.github/workflows/_run-behat-tests.yml
    needs:
      - seed_dynamodb
      - workflow_variables
    with:
      workspace: ${{ needs.workflow_variables.outputs.workspace_name }}
    secrets:
      AWS_ACCESS_KEY_ID_ACTIONS: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      AWS_SECRET_ACCESS_KEY_ACTIONS: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
      ONE_LOGIN_OTP_SECRET: ${{ secrets.ONE_LOGIN_OTP_SECRET }}
      ONE_LOGIN_CREDENTIALS: ${{ secrets.ONE_LOGIN_CREDENTIALS }}
      ONE_LOGIN_USER_PASSWORD: ${{ secrets.ONE_LOGIN_USER_PASSWORD }}
    if: |
      always() &&
      needs.workflow_variables.result == 'success' &&
      needs.seed_dynamodb.result == 'success'

  slack_notify:
    name: notify of result
    uses: ./.github/workflows/_slack-notification.yml
    needs:
      - run_behat_suite
      - workflow_variables
    with:
      template: successful_dev_build.txt
      workflow_status: ${{ needs.run_behat_suite.result }}
      workspace: ${{ needs.workflow_variables.outputs.workspace_name }}
    secrets:
      webhook: ${{ secrets.DEV_SLACK_WEB_HOOK }}
    if: |
      always() &&
      needs.run_behat_suite.result == 'success'

  # Required end of workflow job
  end_of_workflow:
    name: end of workflow
    runs-on: ubuntu-latest
    needs:
      - workflow_variables
      - update_documentation
      - resolve_docker_tag
      - docker_build_scan_push
      - run_behat_suite
      - terraform_apply_environment
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Calculate Step Duration
        id: calculate_durations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python ./scripts/pipeline/output_step_timing/step_timing.py -json '{
            "test node dependencies / unit-test": ["run tests with jest"],
            "build, test, scan and push / docker_build_scan_push": ["docker unit tests", "docker integration and acceptance tests"],
            "run behat tests against environment / build-web": ["run behat test suite"]
          }'

      - name: Create a table with job durations and set as output
        id: create_table
        run: |
          {
            echo ${{ needs.docker_build_scan_push.outputs.matrix_job_names }}
            echo "| Job | Step | Duration |"
            echo "| --- | --- | --- |"
            jobs=$(echo '${{ steps.calculate_durations.outputs.jobs }}' | jq -r '.[]')
            steps=$(echo '${{ steps.calculate_durations.outputs.steps }}' | jq -r '.[]')
            durations=$(echo '${{ steps.calculate_durations.outputs.durations }}' | jq -r '.[]')
            for i in $(seq 0 $(($(echo "$jobs" | wc -l) - 1))); do
              job=$(echo "$jobs" | sed -n "$((i+1))p")
              step=$(echo "$steps" | sed -n "$((i+1))p")
              duration=$(echo "$durations" | sed -n "$((i+1))p")
              echo "| $job | $step | $duration |"
            done
          } >> $GITHUB_STEP_SUMMARY

      - name: workflow has ended without issue
        run: |
          if ${{ contains(needs.run_behat_suite.result, 'success') && contains(needs.terraform_apply_environment.result, 'success') }}; then
            echo "${{ needs.workflow_variables.outputs.safe_branch_name }} PR environment tested, built and deployed"
            echo "Tag Used: ${{ needs.resolve_docker_tag.outputs.docker_tag }}"
            echo "URL: https://${{ needs.workflow_variables.outputs.workspace_name }}.use-lasting-power-of-attorney.service.gov.uk"
            exit 0
          elif [[ ${{ needs.workflow_variables.outputs.specific_path }} = 'docs' ]]; then
            echo 'Ending docs workflow'
            exit 0
          else
            echo "Previous jobs in pipeline failed."
            exit 1
          fi

    if: always()
