name: "[Scheduled] Cleanup PR Workspaces"

on:
  schedule:
    # 6am and 6pm every day except Sundays
    - cron: '0 6,18 * * 0-6'
  workflow_call:
    secrets:
      OPG_USE_A_LPA_DEPLOY_KEY_PRIVATE_KEY:
        required: true

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none
  id-token: write

jobs:
  terraform_environment_cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: "Set terraform version"
        id: set-terraform-version
        uses: ministryofjustice/opg-github-actions/actions/terraform-version@b605e1e2c94b399e8139c4c2be2c8730700e0004 # v4.5.2
        with:
          terraform_directory: ./terraform/environment

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ steps.set-terraform-version.outputs.version }}
          terraform_wrapper: false

      - uses: ministryofjustice/opg-github-actions/actions/github-deploy-key@ceeda9d30ec7f6705c819d0b7664b9a79df99a3b # v4.8.0
        with:
          deploy_key: ${{ secrets.OPG_USE_A_LPA_DEPLOY_KEY_PRIVATE_KEY }}

      - name: configure AWS credentials for getting pagerduty token
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ vars.OIDC_PAGERDUTY_TOKEN_ROLE }}
          aws-region: eu-west-1
          role-duration-seconds: 1800
          role-session-name: OPGUseAnLPADevAssumeGithubAction

      - name: set pagerduty token
        run: |
          export TF_VAR_pagerduty_token=$(aws secretsmanager get-secret-value --secret-id \
            shared/pagerduty-token --region eu-west-1 | jq -r '.SecretString' 2>/dev/null)
          echo "::add-mask::$TF_VAR_pagerduty_token"
          echo TF_VAR_pagerduty_token=$TF_VAR_pagerduty_token >> $GITHUB_ENV

      - name: configure AWS credentials for terraform
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ vars.OIDC_TERRAFORM_ROLE_DEVELOPMENT }}
          aws-region: eu-west-1
          role-duration-seconds: 3600
          role-session-name: OPGUseAnLPATerraformGithubAction

      - name: terraform init
        working-directory: ./terraform/environment
        run: terraform init -input=false

      - name: clean up ephemeral environments
        working-directory: ./terraform/environment
        run: |
          ../../scripts/pipeline/workspace_cleanup/workspace_cleanup.sh $(../../scripts/pipeline/workspace_cleanup/get_workspaces_linux)
