name: "[Scheduled] Generate scan report"

on:
  schedule:
    # Every Monday, at 4pm UTC
    - cron: '00 16 * * 1'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222 # pin@v3
      - uses: ministryofjustice/opg-repository-scanner@latest
