name: Generate scan report

on:
  push:
    branches:
      - "main"
  schedule:
    # Every Monday, at 4pm UTC
    - cron: '00 16 * * 1'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3
      - uses: ministryofjustice/opg-repository-scanner@latest
